name: cltvspj
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.1.0
  url_launcher: ^6.3.2
  timezone: ^0.10.1
  provider: ^6.1.5
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  fl_chart: ^1.1.1
  currency_text_input_formatter: ^2.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  app_settings: ^7.0.0
  sentry_flutter: ^9.13.0
  font_awesome_flutter: ^10.12.0
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  sentry_dart_plugin: ^3.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/imgs/
    - assets/icons/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: cltvspj
  org: victorzarzar
